export const REACT_API_DOMAIN = process.env.REACT_APP_WORKSPACE_ENDPOINT;

export const REACT_APP_AUTH0_DOMAIN = process.env.REACT_APP_AUTH0_DOMAIN;
export const REACT_APP_AUTH0_CLIENT_ID = process.env.REACT_APP_AUTH0_CLIENT_ID;
export const REACT_APP_AUTH0_CLIENT_S = process.env.REACT_APP_AUTH0_CLIENT_S;